### ISSUE TITLE
pre-commit hook: `python not found`

### ISSUE THREAD

**Issue by kenodegard** [conda/infra#570]
When running the new pre-commit hook on my local machine I get a `python not found` error (for whatever reason my system has `python3` not `python`). Unfortunately the "correct" solution (AFAIK) will need us to rework the hook into an installable python executable:

```yaml
# .pre-commit-config.yaml
- repo: local
    hooks:
      - id: sort-json
        name: Sort json files alphabetically
        language: python      ← here
        entry: sort-json      ← and here
        files: ^.clabot$
        args: [--sort-keys=contributors]
```

In which case we need to reorganize this as a Python module and include a `pyproject.toml` and `setup.cfg` which in turn makes me wonder if we just want to implement this in our actions repo or define a new hooks repo for these customizations?

cc: @jezdez
